#!/usr/bin/env bash
#
# setup-signing.sh
#
# Per-machine signing setup so TCC grants (Accessibility, Screen Recording)
# persist across rebuilds. Detects this machine's Apple Development cert,
# writes Local.xcconfig with DEVELOPMENT_TEAM, then runs xcodegen.
#
# Run once per machine. Re-run after switching Apple ID.
#
# Why this matters: ad-hoc signing changes the binary's cdhash on every
# rebuild. TCC keys grants by cdhash + cert chain, so ad-hoc rebuilds wipe
# the grant. Signing with a stable cert keeps the Designated Requirement
# identical, so grants stick.
#

set -euo pipefail

cd "$(dirname "$0")/.."

LOCAL_XCCONFIG="Local.xcconfig"

# Pull first valid Apple Development identity. Format:
#   "Apple Development: name@example.com (TEAMID12)"
TEAM_LINE=$(security find-identity -v -p codesigning 2>/dev/null \
    | grep -E '"Apple Development:' | head -1 || true)

if [[ -z "$TEAM_LINE" ]]; then
    cat <<EOF
✗ No Apple Development cert found on this machine.

Fix:
  1. Open Xcode → Settings → Accounts
  2. Add your Apple ID (free account is fine)
  3. Select your team → "Manage Certificates" → "+" → Apple Development
  4. Re-run this script

EOF
    exit 1
fi

# Extract cert SHA from the find-identity line. Format example:
#   "  1) <40-hex-SHA> "Apple Development: name@example.com (XXXXXXXXXX)""
CERT_SHA=$(echo "$TEAM_LINE" | sed -E 's/^[[:space:]]*[0-9]+\)[[:space:]]+([A-F0-9]{40}).*/\1/')
if ! [[ "$CERT_SHA" =~ ^[A-F0-9]{40}$ ]]; then
    echo "✗ Failed to parse cert SHA from: $TEAM_LINE"
    exit 1
fi

# Real team ID lives in the cert's subject OU field. The parens in the
# CN label happen to match for paid teams, but Personal Teams put a
# different identifier there, so always read OU from the cert itself.
TEAM_ID=$(security find-certificate -c "Apple Development" -p 2>/dev/null \
    | openssl x509 -noout -subject -nameopt RFC2253 2>/dev/null \
    | sed -nE 's/.*OU=([A-Z0-9]+).*/\1/p' | head -1)
if ! [[ "$TEAM_ID" =~ ^[A-Z0-9]+$ ]]; then
    echo "✗ Failed to parse team ID (OU) from Apple Development cert"
    exit 1
fi

echo "✓ Found Apple Development cert. Team ID: $TEAM_ID  SHA: ${CERT_SHA:0:12}…"

cat > "$LOCAL_XCCONFIG" <<EOF
// AUTO-GENERATED by scripts/setup-signing.sh. Do not commit.
// Per-machine signing identity. Re-run the script if your cert changes.
DEVELOPMENT_TEAM = $TEAM_ID
CODE_SIGN_IDENTITY = $CERT_SHA
EOF

echo "✓ Wrote $LOCAL_XCCONFIG"

if ! command -v xcodegen >/dev/null 2>&1; then
    echo "✗ xcodegen not installed. Run: brew install xcodegen"
    exit 1
fi

echo "→ Regenerating Xcode project"
xcodegen generate >/dev/null

echo "→ Resetting TCC entries for com.agentnotch.app (stale ad-hoc grants)"
tccutil reset All com.agentnotch.app >/dev/null 2>&1 || true

echo ""
echo "✓ Done. Next:"
echo "    1. Build in Xcode (⌘R) or with xcodebuild"
echo "    2. Grant the three permissions in onboarding"
echo "    3. Grants now stick across rebuilds"
